POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "kim",
  "password": "developer"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "park",
    "password": "donno"
}
