POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "1. React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 7,
  "userId": "68bec3f3589860efd9290e0f"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "2. Go To Statement Considered Harmful",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": 5,
  "userId": "68bec3f3589860efd9290e0f"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "3. Canonical string reduction",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
  "likes": 12,
  "userId": "68bec3f6589860efd9290e11"
}
